import { AgentDef } from '../types';

export const INITIAL_AGENTS: AgentDef[] = [
  {
    id: 'agent-orchestrator',
    name: 'Orchestrator Agent',
    arabicName: 'وكيل التنسيق وإدارة العمليات',
    role: 'Orchestrator',
    description: 'Directs the recovery pipeline, enforces approval gates, and coordinates specialized agents.',
    status: 'ACTIVE',
    allowedTools: ['dispatch_agent', 'check_approval_policy', 'notify_manager'],
    deniedTools: ['execute_bank_transfer', 'settle_dispute_without_approval'],
    maxFinancialExposureUsd: 0,
    tasksCompleted: 412,
    lastActive: 'Just now',
  },
  {
    id: 'agent-discovery',
    name: 'Discovery Agent',
    arabicName: 'وكيل استكشاف التسرب المالي',
    role: 'Discovery',
    description: 'Scans accounts payable ledgers, purchase orders, and payment histories for anomalies.',
    status: 'ACTIVE',
    allowedTools: ['scan_ledger', 'flag_duplicate', 'query_transactions'],
    deniedTools: ['modify_ledger', 'send_external_email'],
    maxFinancialExposureUsd: 0,
    tasksCompleted: 894,
    lastActive: '2m ago',
  },
  {
    id: 'agent-contract',
    name: 'Contract Agent',
    arabicName: 'وكيل العقود والشروط التجارية',
    role: 'Contract Analyst',
    description: 'Parses procurement agreements, extracting prompt-payment discounts, volume rebate tiers, and SLA terms.',
    status: 'ACTIVE',
    allowedTools: ['read_contract', 'extract_rebate_rule', 'compare_terms'],
    deniedTools: ['alter_contract', 'delete_document'],
    maxFinancialExposureUsd: 0,
    tasksCompleted: 156,
    lastActive: '12m ago',
  },
  {
    id: 'agent-invoice',
    name: 'Invoice Agent',
    arabicName: 'وكيل مطابقة الفواتير',
    role: '3-Way Matcher',
    description: 'Performs 3-way matching between vendor invoices, purchase orders, and goods receipts.',
    status: 'ACTIVE',
    allowedTools: ['compare_line_items', 'verify_tax_math', 'check_receipts'],
    deniedTools: ['write_payment_record'],
    maxFinancialExposureUsd: 0,
    tasksCompleted: 1420,
    lastActive: '5m ago',
  },
  {
    id: 'agent-freight',
    name: 'Freight Agent',
    arabicName: 'وكيل تدقيق الشحن واللوجستيات',
    role: 'Logistics Auditor',
    description: 'Audits carrier bills of lading, fuel surcharges, dimensional weight, and unauthorized accessorials.',
    status: 'ACTIVE',
    allowedTools: ['audit_tariff', 'verify_bill_of_lading', 'flag_surcharge'],
    deniedTools: ['issue_carrier_credit'],
    maxFinancialExposureUsd: 0,
    tasksCompleted: 310,
    lastActive: '1h ago',
  },
  {
    id: 'agent-evidence',
    name: 'Evidence Agent',
    arabicName: 'وكيل توثيق وسلسلة الأدلة',
    role: 'Forensic Evidence Assembler',
    description: 'Packages incontrovertible document citations, transaction IDs, and contractual clauses.',
    status: 'ACTIVE',
    allowedTools: ['link_document_excerpt', 'generate_evidence_package'],
    deniedTools: ['fabricate_citation', 'modify_timestamp'],
    maxFinancialExposureUsd: 0,
    tasksCompleted: 388,
    lastActive: '18m ago',
  },
  {
    id: 'agent-calculation',
    name: 'Calculation Agent',
    arabicName: 'وكيل الحسابات الرياضية القطعية',
    role: 'Deterministic Math Validator',
    description: 'Calculates exact financial differences using code-based decimal arithmetic, never LLM estimations.',
    status: 'ACTIVE',
    allowedTools: ['calculate_difference', 'apply_discount_formula', 'convert_fx'],
    deniedTools: ['round_arbitrarily', 'override_tolerance'],
    maxFinancialExposureUsd: 0,
    tasksCompleted: 1840,
    lastActive: 'Just now',
  },
  {
    id: 'agent-verification',
    name: 'Verification Agent',
    arabicName: 'وكيل التحقق والرقابة',
    role: 'Audit Quality Assurance',
    description: 'Verifies evidence completeness and assigns recovery confidence before claim generation.',
    status: 'ACTIVE',
    allowedTools: ['verify_evidence_chain', 'evaluate_confidence'],
    deniedTools: ['bypass_human_gate'],
    maxFinancialExposureUsd: 0,
    tasksCompleted: 512,
    lastActive: '8m ago',
  },
  {
    id: 'agent-claim',
    name: 'Claim Agent',
    arabicName: 'وكيل صياغة المطالبات',
    role: 'Claim Drafter',
    description: 'Drafts formal, itemized recovery notices with contractual references for supplier dispute resolution.',
    status: 'ACTIVE',
    allowedTools: ['draft_claim_letter', 'attach_evidence_dossier'],
    deniedTools: ['send_claim_exceeding_threshold'],
    maxFinancialExposureUsd: 500, // Autonomous limit
    tasksCompleted: 142,
    lastActive: '30m ago',
  },
  {
    id: 'agent-negotiation',
    name: 'Negotiation Agent',
    arabicName: 'وكيل التفاوض والردود',
    role: 'Dispute Handler',
    description: 'Monitors vendor replies, clarifies invoice references, and alerts operators if disputes escalate.',
    status: 'ACTIVE',
    allowedTools: ['read_vendor_reply', 'draft_clarification'],
    deniedTools: ['accept_binding_settlement_without_approval'],
    maxFinancialExposureUsd: 0,
    tasksCompleted: 88,
    lastActive: '2h ago',
  },
  {
    id: 'agent-recovery',
    name: 'Recovery Agent',
    arabicName: 'وكيل تسوية واسترداد الأموال',
    role: 'Settlement Verifier',
    description: 'Verifies bank credit deposits and formal credit memos before recording a verified recovery.',
    status: 'ACTIVE',
    allowedTools: ['match_credit_memo', 'verify_bank_deposit', 'log_recovery'],
    deniedTools: ['mark_recovered_without_proof'],
    maxFinancialExposureUsd: 0,
    tasksCompleted: 94,
    lastActive: '1h ago',
  },
  {
    id: 'agent-learning',
    name: 'Learning Agent',
    arabicName: 'وكيل التعلم وتحسين النماذج',
    role: 'Continuous Improvement',
    description: 'Analyzes past supplier settlement outcomes to optimize detection recall and reduce false positives.',
    status: 'ACTIVE',
    allowedTools: ['analyze_settlement_history', 'tune_tolerance_rules'],
    deniedTools: ['alter_security_policies'],
    maxFinancialExposureUsd: 0,
    tasksCompleted: 67,
    lastActive: '4h ago',
  },
];
